In xref:Main.adoc[ProtoFlux], the context of any given node group determines many factors on how the ProtoFlux is internally processed. A few things that context will affect include how control flow is handled, what concepts the ProtoFlux is aware of, and how the ProtoFlux interacts with FrooxEngine, if at all.

There is only one baseline context available for ProtoFlux nodes, that being the ExecutionContext. There exist extensions to this context, with the only one being FrooxEngineContext. More contexts are to be expected in the future, such as a state machine context, an audio DSP context, and a shader context. 

== ExecutionContext
The ExecutionContext context mirrors traditional link:https://en.wikipedia.org/wiki/Imperative_programming[imperative programming]. As of the time of writing, all ProtoFlux is under this context.

ExecutionContext is the most basic context for control flow in ProtoFlux. It establishes the concept of xref:Impulses.adoc[impulses] (along with xref:Async.adoc[async] control flow) and writes (but only to a ProtoFlux-specific value store, such as a xref:Local.adoc[Local] or xref:Store.adoc[Store]). 

=== FrooxEngineContent