ProtoFlux is a Node based scripting language that can be manipulated in 3D space using the ProtoFlux Tool.

[quote,'https://resonite.com/features.html[https://resonite.com/features.html]']
ProtoFlux is the crown jewel of our creative tools - the most powerful visual programming language that our experienced team has designed to date, which lets you quickly prototype and build anything from simple interactions to complex games and systems - with full real-time collaboration support and immediate feedback. Build anything from avatar and world interactivity, to complex systems, and games.


.Usage
[%collapsible]
====
ProtoFlux is represented in the world as nodes that can be selected from the xref:Node Browser.adoc[ProtoFlux Node Browser], and spawned from the xref:Tool.adoc[ProtoFlux Tool].

You can easily spawn a ProtoFlux Tool from the Resonite Essentials folder included in your Inventory to begin scripting with ProtoFlux (The tool itself is found in the Tools folder in the Essentials Folder).

To view a list of nodes, go to ProtoFlux Browser Version for a style like in game, or go to Alphabetical list of all nodes to see a comprehensive list. Every node page links back to both lists.

To begin using Protoflux first spawn then equip the ProtoFlux Tool from the folder mentioned above. Once equipped, the Protoflux node browser can be found in your Context menu. To select a node, double click the node with the Protoflux Tool. This will make the name of the node appear above the tool to show it has been selected. Then double click, to spawn the selected node.

You can also quick select nodes that already exist by tapping Secondary while pointing at the node.

Nodes can be connected by pointing the laser at a node's connection point and holding Primary (Trigger for most controllers, or Left Click), then dragging the wire and letting go of Primary while pointing at another node's connection point. They can then be cut by intersecting the red line that comes out the tip of the ProtoFlux Tool while holding Primary. 
====