:experimental:

.Why not help the official wiki?
[%collapsible]
====

I don't want to **officially** provide false information. Keep in mind I am a complete beginner that wrote this wiki, to learn by teaching.

====
''''

== Running on Arch Linux

. Install the following: +
`# pacman -S ffmpeg libxcb assimp rtmpdump`

. Install link:https://github.com/Babakinha/ResoniteLinuxFix#how-to-install[ResoniteLinuxFix] following its instructions; there's no need to compile it.
. Enjoy Resonite.

NOTE: Check the Logs after playing for a while, it's in the root directory of Resonite. This will tell you if you are missing any additional dependencies.


== Desktop Keybindings

. Tap kbd:[F5] for Thirdperson.

.Tools
. Tap kbd:[1] to de-equip your tools.
. kbd:[2] -> Dev Tool
. kbd:[3] -> Proto Flux Tool
. kbd:[4] -> Material Tool
. kbd:[5] -> Shape Tool
. kbd:[6] -> Light Tool
. kbd:[7] -> Grabbable Setter Tool
. kbd:[8] -> Character Collider Setter Tool
. kbd:[9] -> Microphone (Screen Mode)

.Movement
. Tap kbd:[C] to toggle Duck, hold kbd:[C] to be able to let go of being Ducked.
. Hold kbd:[LShift] to Run.
. Tap kbd:[Z] to toggle Sneak.

.Speech
. Turn off the microphone (at the top-left corner of main menu, there is a Mic icon with an X at its top), then hold kbd:[Mouse4] (back button) to Push To Talk.
. **Only if you installed `Inventory -> Resonite Essentials -> Accessibility -> Mute Helper`**: +
Tap kbd:[H] to quickly bring up a text prompt.

.Dev Tool
. kbd:[R] to select the slot/object you are looking at; kbd:[T] can then be tapped to Open its Inspector.
. kbd:[I] to open the Inspector at Root (global / the world and all of its components).

.UI Focus (to use inspectors easily)
. kbd:[LCtrl + LClick] to focus on an inspector, then afterwards...
- kbd:[LCtrl + RClick] to move the X and Y axis in a 2D fashion (side to side, up or down).
- kbd:[LCtrl + ScrollWheel] to Zoom In and Out.
