:experimental:
ifdef::env-github[]
:icons:
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== How-to
.Setup
. Install the https://github.com/Gawdl3y/Resolute?tab=readme-ov-file#downloads[Resolute] modding GUI; for Arch Linux it'd be running: `paru -Syu resolute-bin webkit2gtk-4.1`

. Open Resolute to install the mod manager, then install Resonite Mod Settings and CherryPick. Afterwards you can close Resolute.

. Read FluxSDK's https://flux-sdk.samsmucny.com/ProtoGraph/Getting-Started.html[Getting Started].

. Ensure CachyOS (or Arch Linux with the 'fish' shell) is able to know the paths of dotnet installed software:
- Edit `~/.config/fish/config.fish`: +
[fish]
----
set -gx DOTNET_ROOT /usr/share/dotnet
fish_add_path /usr/share/dotnet
fish_add_path $HOME/.dotnet/tools
----

.Using Claude
. Ensure Claude Code is already installed.

. Download a ZIP of the https://github.com/felikcat/protoflux-claude-template[protoflux-claude-template] repository, then go into its directory to then run `claude`.

. The agents will automatically handle what model to use based on the task. Keep in mind that I specified Opus instead of Sonnet and it uses ultrathink for maximum accuracy.
- If the costs aren't reasonable for you, you can set the agents that use Opus to use Sonnet instead, and remove 'ultrathink' from CLAUDE.md.

. Have fun.
