:experimental:
ifdef::env-github[]
:icons:
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== How-to
.Setup
. Install the https://github.com/Gawdl3y/Resolute?tab=readme-ov-file#downloads[Resolute] modding GUI; for Arch Linux it'd be running: `paru -Syu resolute-bin webkit2gtk-4.1`

. Open Resolute to install the mod manager, then install Resonite Mod Settings, CherryPick, and HotReloadLib. Afterwards you can close Resolute.

. Read FluxSDK's https://flux-sdk.samsmucny.com/ProtoGraph/Getting-Started.html[Getting Started].

. Ensure CachyOS (or Arch Linux with the 'fish' shell) is able to know the paths of dotnet installed software:
- Edit `~/.config/fish/config.fish`: +
[fish]
----
set -gx DOTNET_ROOT /usr/share/dotnet
fish_add_path /usr/share/dotnet
fish_add_path $HOME/.dotnet/tools
----

.Using Google Gemini
. Ensure Gemini CLI is already installed.

. Download a ZIP of the https://github.com/felikcat/protoflux-gemini-template[protoflux-gemini-template] repository, then go into its directory to then run `gemini`.

. I would recommend using Gemini 3 Flash which you can select using `/model`, it's good enough and relatively quick.

. Have fun. Do keep in mind that you have to push it towards using more optimal solutions at times, such as using ProtoDust for particles.
