:experimental:
ifdef::env-github[]
:icons:
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:toc:

WARNING: If Envision recommends to set the AMD GPU power profile to VR, don't. It is now bad advice as your performance will decrease. +
All instructions are tested only on CachyOS and actively maintained. My unmaintained instructions https://gist.github.com/felikcat/b23f4c483bbf5390253f0bc562275639[are here] for Arch Linux, openSUSE, Ubuntu, and Debian respectively.

== Better video playback support
Install https://flathub.org/apps/com.vysp3r.ProtonPlus[ProtonPlus], open it, and add the latest Proton-GE RTSP. Restart Steam after doing so.

In Steam's Library, kbd:[RClick] on Resonite, kbd:[LClick] properties, go to Compatibility and force use of "GE-Proton10-26-rtsp20" (if it's newer, use that instead).


== Tracking down crashes
Take a look at https://github.com/alvr-org/ALVR/wiki/Linux-Troubleshooting[ALVR's Linux Troubleshooting] page.

.Where Resonite logs are located:
- `/home/YOUR_USER/.local/share/Steam/steamapps/compatdata/2519830/pfx/drive_c/users/steamuser/AppData/LocalLow/Yellow Dog Man Studios/Resonite` -> `Player.log`
- `/home/YOUR_USER/.local/share/Steam/steamapps/common/Resonite/Logs`

.Tips
. If you see a ton of SteamVR errors in `Player.log` after a crash, switch to a different VR backend. I had this issue on Monado. +
. If the game will not open with SteamVR active, close SteamVR, then reopen it.


== Using Envision
=== Combining with wlx-overlay-s
This is so you can utilize your desktop in VR, and also have a wrist watch akin to XSOverlay.

Set `wlx-overlay-s --openxr --show` as the Autostart Command on your Envision profile.

Read this https://github.com/galister/wlx-overlay-s?tab=readme-ov-file#getting-started[Getting Started page] to learn how to use wlx-overlay-s.


== How to support and use the Bigscreen Beyond 1/2/2e on CachyOS

Download the kernel patch from https://lvra.gitlab.io/docs/other/bigscreen-beyond[LVRA's wiki page on the Bigscreen Beyond 1/2/2e].

Open the 'CachyOS Kernel Manager'.

Click on 'Configure'.

Put the 'Custom package name' as `$pkgbase-bigscreen`.

Go to 'Patches' then add the Bigscreen Beyond patch using 'Add local patch' and put in the kernel patch you downloaded. After that's done, build the kernel.

Once it's done building, be sure to install its build packages. Afterwards, reboot into the new LTS kernel to enjoy the Bigscreen Beyond!

== Bigscreen Beyond low microphone volume workaround

`sudo pacman -S easyeffects lsp-plugins-lv2`

Open EasyEffects, go to Preferences, and disable 'Process All Output Streams'.

Go to PipeWire -> General -> uncheck 'Use Default Input' and set it to "Beyond Analog Stereo".

Go to Input -> Add Effect: 'Autogain', and leave its settings at the defaults.

Now you can set the input to EasyEffects Source in your desired application or game.

NOTE: The noise supression inside VRChat and Resonite should mask the static or background noise, but you can optionally add an effect to reduce noise.


== More information (the Linux VR Adventures Wiki); it's recommended to read this last
https://lvra.gitlab.io/docs/resonite/
